### ISSUE TITLE
provide sample reports

### ISSUE THREAD

**Issue by jonpday** [kalenjordan/custom-reports#11]
can you please paste example SQL and corresponding chart configurations into README.md or elsewhere as a starting point? thx

**Comment by kevincal** [comment]
Suggestions:
1) Would be cool to start a companion github project where people could submit their recipes openly. 
2) Simple str pattern search for DROP, TRUNCATE, DELETE in the SQL which would error out to add a basic layer of idiocy protection.

-Kevin

**Comment by kalenjordan** [comment]
@kevincal 
1. absolutely - love that idea.  I have a few random ones on gist - maybe you can fire that up.
2. agreed.

**Comment by kalenjordan** [comment]
@clojens  you are a *machine*.  Sorry I don't have time to read all that right now.

**Comment by peterjaap** [comment]
@clojens could you separate your suggestion out to a new ticket? Closing this one.

**Comment by peterjaap** [comment]
Thanks so much @sreichel, I've placed that in the extension. Unfortunately (and I can't figure out why) I am able to see your commits but I'm not able to find them in git repo itself and I'm not able to cherry-pick them. I therefore manually added it to the extension. It's now attributed to me though instead of you, sorry 'bout that.

https://github.com/kalenjordan/custom-reports/commit/e19b0330acc6e2be88b777f52fd8b997a7b094d4
